### ISSUE TITLE
Define account_file_path

### ISSUE THREAD

**Issue by kevvdp** [hashicorp/vault-guides#199]
Good day! I'm trying to get this guide up and running, but having some issues on my end.

One question I have is, what is the `account_file_path`?

As mentioned in the [gcp-readme](https://github.com/hashicorp/vault-guides/blob/master/operations/gcp-kms-unseal/README.md), I need to provide a .json file for my project. What is the file and where can I get it?

```sh
gcloud-project = "my-project"
account_file_path = "/usr/gcp/my-project.json"  # <----- what is this?
```

Initially, I thought this was the service account .json file, but I'm trying to use the terraform file to create the service account. 

Any help is appreciated, thanks!

**Comment by yhyakuna** [comment]
@kevvdp 
It's referring to the GCP service account file (JSON) containing your account information necessary to connect to your GCP account (basically your credentials).  

If you don't have one, please refer to the GCP documentation --> https://cloud.google.com/docs/authentication/getting-started
