### ISSUE TITLE
vault + k8s + minikube : Enterprise versus OSS Vault in the context of k8s guide...

### ISSUE THREAD

**Issue by nrvale0** [hashicorp/vault-guides#23]
Vault Enterprise is not strictly required for the k8s guide except that Auto Unseal is an Enterprise feature. The verbiage in the guide should be adjusted to make that more clear.

@bensojona

**Comment by bensojona** [comment]
@nrvale0 got it. Maybe we just start with deploying HashiStack on k8s using OSS, then we can create a separate guide that focuses on how to modify it to leverage the auto-unseal functionality in Enterprise to remove the need to unseal manually.

**Comment by nrvale0** [comment]
@bensojona Absolutely. I only chose minikube in previous work because it made it faster to iterate and do local dev. For next guide I'll llikely leverage GKE (easiest way to deploy k8s in cloud via Terraform) and leverage Google KMS. In the process, can probably generate autounseal guide for GCP if that collateral does not already exist.
