### ISSUE TITLE
Please document required vagrant addons

### ISSUE THREAD

**Issue by Nadav-Ruskin** [hashicorp/vault-guides#265]
Foreword: I am not experienced with vagrant. I want to learn how to use Vault to manage SSH keys. The official documentation lead me to the `vagrant-local` tutorial on this repository.

Steps to reproduce, using a fresh `vagrant` installation:
```
vault-guides/identity/ssh-ca/vagrant-local$ vagrant up
Bringing machine 'vault' up with 'virtualbox' provider...
Bringing machine 'client' up with 'virtualbox' provider...
==> vault: Box 'bento/centos-7.6' could not be found. Attempting to find and install...
    vault: Box Provider: virtualbox
    vault: Box Version: 201812.27.0
==> vault: Loading metadata for box 'bento/centos-7.6'
    vault: URL: https://vagrantcloud.com/bento/centos-7.6
==> vault: Adding box 'bento/centos-7.6' (v201812.27.0) for provider: virtualbox
    vault: Downloading: https://vagrantcloud.com/bento/boxes/centos-7.6/versions/201812.27.0/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> vault: Successfully added box 'bento/centos-7.6' (v201812.27.0) for 'virtualbox'!
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The 'hosts' provisioner could not be found.
```

I've solved the problem (I think) by running `vagrant plugin install vagrant-hosts && vagrant provision`.
Please document any required `vagrant` plugins (are there more?) in the tutorial's readme file.

**Comment by FrameBassman** [comment]
Suggest to install `vagrant-hosts` plugin if it is not installed
Created PR for that

**Comment by FrameBassman** [comment]
@Nadav-Ruskin, Fix was delivered to `master` branch. I think you can close issue)

**Comment by Nadav-Ruskin** [comment]
Hey @FrameBassman , thanks for the fix. Unfortunately I don't have access to a work station where I can poof it, but it looks good to me! 👍

**Comment by FrameBassman** [comment]
@yhyakuna could you close this issue?

**Comment by yhyakuna** [comment]
This should be fixed in [PR 265](https://github.com/hashicorp/vault-guides/pull/312), so I'm closing this.
