### ISSUE TITLE
Provision Vault keeps failing for Best Practice and Quick Start

### ISSUE THREAD

**Issue by nedshawa** [hashicorp/vault-guides#53]
plans fails with the following error:

* module.vault_aws.aws_autoscaling_group.vault: 1 error(s) occurred:

* aws_autoscaling_group.vault: "vault-best-practices-vault-2018062807014907740000001520180628070158351300000016": Waiting up to 10m0s: Need at least 3 health
y instances in ELB, have 0. Most recent activity: {
  ActivityId: "e5959114-cc76-434d-8879-9655845163f2",
  AutoScalingGroupName: "vault-best-practices-vault-2018062807014907740000001520180628070158351300000016",
  Cause: "At 2018-06-28T07:01:59Z a user request created an AutoScalingGroup changing the desired capacity from 0 to 3.  At 2018-06-28T07:02:12Z an instance
was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 3.",
  Description: "Launching a new EC2 instance: i-0f4c77e6786a974e6",
  Details: "{\"Subnet ID\":\"subnet-07602c814038319a7\",\"Availability Zone\":\"ap-southeast-2a\"}",
  EndTime: 2018-06-28 07:02:47 +0000 UTC,
  Progress: 100,

  StartTime: 2018-06-28 07:02:15.184 +0000 UTC,
  StatusCode: "Successful"
}

**Comment by bensojona** [comment]
@nedshawa are you still experiencing this issue?

**Comment by bensojona** [comment]
This should be resolved with https://github.com/hashicorp-modules/vault-aws/pull/23
