### ISSUE TITLE
tls-self-signed-cert repo is not public

### ISSUE THREAD

**Issue by kmcquade** [hashicorp/vault-guides#6]
Lines 18 and 29 in the f-add-provision-guides branch

https://github.com/hashicorp/vault-guides/blob/f-add-provision-guides/provision/best-practices/terraform-aws/main.tf#L18

Clear that it's not the tls-private-key repo either, given the vars required

Please make that other repo public so it's easy to use.

**Comment by kmcquade** [comment]
@bensojona - just making sure someone sees this :)

**Comment by bensojona** [comment]
@kmcquade it's public now. Looking to merge all of this into master soon.

**Comment by bensojona** [comment]
@kmcquade Let me know if any other modules required are not public.

**Comment by kmcquade** [comment]
@bensojona thanks for the quick response. Only other issue that I'm encountering is the aws_ami data source. We don't have access to that demo account. Is there a specific packer build we need to use? I'm only using the one in the bastion module; already have my own AMIs with Enterprise Consul and Vault

data "aws_ami" "hashistack" {
  most_recent = true
  owners      = ["362381645759"] # hc-se-demos Hashicorp SE Demos Account

**Comment by kmcquade** [comment]
@bensojona never mind. Figured out that it's in the guides-configuration /hashistack folder

**Comment by bensojona** [comment]
@kmcquade yep - still need to document that part :) 

Hadn't considered what happens when you don't have access to our demo account. Does the `terraform plan` just fail? I may need to make the `owners` attribute an input variable if that's the case.

**Comment by kmcquade** [comment]
@bensojona yeah it fails - can't remember the exact error message but it says something to the effect of "we don't see AMIs matching these attributes in your account." Owners = self is probably a good idea
